Fix instagram image display
ubc/foa-site pull request #3
Opened 2018-03-26 20:13 UTC by michaelha

2018-03-26 20:20 UTC, michaelha commented
@richardtape Please review this as well as #2   Feel free to email/slack dm me to discuss if you have any feedback.  Thanks!

2018-03-29 15:59 UTC, richardtape commented
Looks like you have pushed both commits to this pull request so now there's conflicts. If you could please revise and resolve them, I'll take a look :)

2018-03-29 16:01 UTC, michaelha commented
Will do it right now :)

2018-03-29 16:04 UTC, michaelha commented
@richardtape ready for review.

2018-03-29 19:11 UTC, michaelha reviewed
fix phpcs errors

2018-03-29 19:11 UTC, michaelha commented on foa-site.php
> +			$remote = wp_remote_get( 'https://instagram.com/'.trim( $username ) );
1304 | WARNING | [ ] wp_remote_get() is highly discouraged, please use vip_safe_wp_remote_get() instead.

2018-03-29 19:11 UTC, michaelha commented on foa-site.php
> +				throw new Exception('Instagram did not return a 200.');
1308 | ERROR   | [x] Expected 1 spaces after opening bracket; 0 found
 1308 | ERROR   | [x] Expected 1 spaces before closing bracket; 0 found

2018-03-29 19:11 UTC, michaelha commented on foa-site.php
> +			if ( isset( $insta_array['entry_data']['ProfilePage'][0]['graphql']['user']['edge_owner_to_timeline_media']['edges'] ) ) {
no error.

2018-03-29 19:11 UTC, michaelha commented on foa-site.php
> +				$images = $insta_array['entry_data']['ProfilePage'][0]['graphql']['user']['edge_owner_to_timeline_media']['edges'];
no error.

2018-03-29 19:11 UTC, michaelha commented on foa-site.php
> +            foreach ( $images as $image ) {
1322 | ERROR   | [x] Tabs must be used to indent lines; spaces are not allowed

2018-03-29 19:11 UTC, michaelha commented on foa-site.php
> +                $image['display_src'] = preg_replace( "/^http:/i", "", $image['node']['display_url'] );
1323 | ERROR   | [x] Tabs must be used to indent lines; spaces are not allowed
 1323 | ERROR   | [x] String "/^http:/i" does not require double quotes; use single quotes instead
 1323 | ERROR   | [x] String "" does not require double quotes; use single quotes instead

2018-03-29 19:11 UTC, michaelha commented on foa-site.php
> +                if ( $image['is_video']  == true ) {
1324 | ERROR   | [x] Tabs must be used to indent lines; spaces are not allowed
 1324 | WARNING | [ ] Found: ==. Use strict comparisons (=== or !==).
 1324 | ERROR   | [ ] Use Yoda Condition checks, you must.
 1324 | ERROR   | [x] Expected 1 space before "=="; 2 found

2018-03-29 19:11 UTC, michaelha commented on foa-site.php
> +                    $type = 'video';
1325 | ERROR   | [x] Tabs must be used to indent lines; spaces are not allowed

2018-03-29 19:11 UTC, michaelha commented on foa-site.php
> +                } else {
1326 | ERROR   | [x] Tabs must be used to indent lines; spaces are not allowed

2018-03-29 19:11 UTC, michaelha commented on foa-site.php
> +                    $type = 'image';
1327 | ERROR   | [x] Tabs must be used to indent lines; spaces are not allowed

2018-03-29 19:11 UTC, michaelha commented on foa-site.php
> +                }
1328 | ERROR   | [x] Tabs must be used to indent lines; spaces are not allowed
 1329 | ERROR   | [x] Tabs must be used to indent lines; spaces are not allowed

2018-03-29 19:11 UTC, michaelha commented on foa-site.php
> +                    'description'   => __( $image['node']['edge_media_to_caption']['edges'][0]['node']['text'], 'wpiw' ),
1330 | ERROR   | [x] Tabs must be used to indent lines; spaces are not allowed
 1330 | WARNING | [x] Array double arrow not aligned correctly; expected 1 space(s) between "'description'" and double arrow, but found 3.
 1330 | ERROR   | [ ] The $text arg must be a single string literal, not "$image['node']['edge_media_to_caption']['edges'][0]['node']['text']".

2018-03-29 19:11 UTC, michaelha commented on foa-site.php
> +                    'link'		  	=> '//instagram.com/p/' . $image['node']['shortcode'],
1331 | ERROR   | [x] Tabs must be used to indent lines; spaces are not allowed
 1331 | ERROR   | [x] Spaces must be used for mid-line alignment; tabs are not allowed
 1331 | WARNING | [x] Array double arrow not aligned correctly; expected 8 space(s) between "'link'" and double arrow, but found 10.

2018-03-29 19:11 UTC, michaelha commented on foa-site.php
> +                    'time'		  	=> $image['node']['taken_at_timestamp'],
1332 | ERROR   | [x] Tabs must be used to indent lines; spaces are not allowed
 1332 | ERROR   | [x] Spaces must be used for mid-line alignment; tabs are not allowed
 1332 | WARNING | [x] Array double arrow not aligned correctly; expected 8 space(s) between "'time'" and double arrow, but found 10.
 1333 | ERROR   | [x] Tabs must be used to indent lines; spaces are not allowed
 1333 | ERROR   | [x] Spaces must be used for mid-line alignment; tabs are not allowed
 1333 | WARNING | [x] Array double arrow not aligned correctly; expected 4 space(s) between "'comments'" and double arrow, but found 6.
 1334 | ERROR   | [x] Tabs must be used to indent lines; spaces are not allowed
 1334 | ERROR   | [x] Spaces must be used for mid-line alignment; tabs are not allowed
 1334 | WARNING | [x] Array double arrow not aligned correctly; expected 7 space(s) between "'likes'" and double arrow, but found 9.
 1335 | ERROR   | [x] Tabs must be used to indent lines; spaces are not allowed
 1335 | ERROR   | [x] Spaces must be used for mid-line alignment; tabs are not allowed
 1335 | WARNING | [x] Array double arrow not aligned correctly; expected 3 space(s) between "'thumbnail'" and double arrow, but found 5.
 1336 | ERROR   | [x] Tabs must be used to indent lines; spaces are not allowed
 1336 | ERROR   | [x] Spaces must be used for mid-line alignment; tabs are not allowed
 1336 | WARNING | [x] Array double arrow not aligned correctly; expected 8 space(s) between "'type'" and double arrow, but found 10.
 1336 | ERROR   | [x] Each array item in a multi-line array declaration must end in a comma
 1337 | ERROR   | [x] Tabs must be used to indent lines; spaces are not allowed
 1338 | ERROR   | [x] Tabs must be used to indent lines; spaces are not allowed

2018-03-29 19:11 UTC, michaelha commented on foa-site.php
> +			$remote = wp_remote_get( 'https://instagram.com/'.trim( $username ) );
ignore.

2018-03-29 19:39 UTC, michaelha commented
@richardtape I've addressed phpcs error messages. Please review this PR.  Thanks.

2018-03-29 19:52 UTC, richardtape requested changes
This is nearly ready to go. Just a couple tweaks.

2018-03-29 19:52 UTC, richardtape commented on foa-site.php
> +				throw new Exception( 'Unable to communicate with Instagram.' );
Conditionals should always have braces. i.e.

```
if ( is_wp_error( $remote ) ) {
    throw new Exception( 'Unable to communicate with Instagram.' );
}
```

This applies to a few chunks in this commit.

2018-03-29 19:52 UTC, richardtape commented on foa-site.php
>  			if ( 200 != wp_remote_retrieve_response_code( $remote ) )
I think `!=` should be `!==` to have strict adherence to coding standards

2018-03-29 19:52 UTC, richardtape commented on foa-site.php
> +			$remote = wp_remote_get( 'https://instagram.com/'.trim( $username ) );
Should be spaces either side of the concatenating period. i.e. 

```
$remote = wp_remote_get( 'https://instagram.com/' . trim( $username ) );
```

2018-03-29 19:54 UTC, richardtape commented on foa-site.php
> +			$remote = wp_remote_get( 'https://instagram.com/'.trim( $username ) );
Actually, whilst I'm thinking about it, please also add an `esc_url()` check around the whole URL.

i.e.

```
$remote = wp_remote_get( esc_url( 'https://instagram.com/' . trim( $username ) ) );
```

2018-03-29 19:58 UTC, richardtape requested changes

2018-03-29 19:58 UTC, richardtape commented on foa-site.php
> +			$remote = wp_remote_get( 'https://instagram.com/' . trim( $username ) );
This is my bad, see my other comment on this. I think we should have an `esc_url()` check on this whole URL.

2018-03-29 20:22 UTC, richardtape approved these changes
👍

2018-03-29 20:23 UTC, merged